add code
ZhukovCorp/Task1.1.3 pull request #1
Opened 2023-11-16 18:24 UTC by wvterry

2023-11-17 03:23 UTC, pdasilem requested changes
убрать лишние папки/файлы из пр

2023-11-17 03:23 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoJDBCImpl.java
> +        catch (Exception exception){
Сузить эксепшн

2023-11-17 03:23 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoJDBCImpl.java
> +            Statement statement = connection.createStatement();
закрывать стейтмент и коннекшн после использования

2023-11-17 03:23 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/util/ConnectionManager.java
> +          throw new RuntimeException(e);
зачем выбрасываешь исключение?

2023-11-17 03:23 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/util/PropertiesUtil.java
> +           throw new RuntimeException(e);
аналогично

2023-11-18 15:16 UTC, wvterry commented on src/main/java/jm/task/core/jdbc/dao/UserDaoJDBCImpl.java
> +        catch (Exception exception){
исправлено

2023-11-18 15:16 UTC, wvterry commented on src/main/java/jm/task/core/jdbc/dao/UserDaoJDBCImpl.java
> +            Statement statement = connection.createStatement();
исправлено

2023-11-18 15:17 UTC, wvterry commented on src/main/java/jm/task/core/jdbc/util/ConnectionManager.java
> +          throw new RuntimeException(e);
исправлено

2023-11-18 15:17 UTC, wvterry commented on src/main/java/jm/task/core/jdbc/util/PropertiesUtil.java
> +           throw new RuntimeException(e);
исправлено

2023-11-19 14:16 UTC, pdasilem requested changes

2023-11-19 14:16 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/Main.java
> +        UserDaoJDBCImpl userDao= new UserDaoJDBCImpl();
внедряй через интерфейсы

2023-11-19 14:16 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/dao/UserDaoJDBCImpl.java
> +            Statement statement = connection.createStatement();
в ресурсах трая закрывать

2023-11-19 14:16 UTC, pdasilem commented on src/main/java/jm/task/core/jdbc/util/Util.java
> +public class Util {
это что за цирк? ))
зачем здесь мейн?

2023-11-19 18:15 UTC, wvterry commented on src/main/java/jm/task/core/jdbc/dao/UserDaoJDBCImpl.java
> +            Statement statement = connection.createStatement();
исправлено

2023-11-19 18:36 UTC, wvterry commented on src/main/java/jm/task/core/jdbc/Main.java
> +        UserDaoJDBCImpl userDao= new UserDaoJDBCImpl();
исправлено

2023-11-19 18:44 UTC, wvterry commented on src/main/java/jm/task/core/jdbc/util/Util.java
> +public class Util {
Исправлено

2023-11-20 04:41 UTC, pdasilem approved these changes

2023-11-20 15:50 UTC, merged